# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer_belt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_users', to='reviewer_belt.User'),
        ),
    ]
