# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='name',
        ),
        migrations.AddField(
            model_name='name',
            name='course_desc',
            field=models.TextField(default='1000'),
        ),
        migrations.DeleteModel(
            name='Desc',
        ),
    ]
