# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20180322_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='name',
            name='course_desc',
        ),
        migrations.AddField(
            model_name='name',
            name='desc',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='courses_app.Desc'),
        ),
    ]
