# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_auto_20180322_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='desc',
            field=models.OneToOneField(default='d', on_delete=django.db.models.deletion.CASCADE, to='courses_app.Desc'),
        ),
    ]
